# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
print(np.__version__)
print(np.show_config())

1.24.2
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['openblas\\lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['openblas\\lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['openblas\\lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None

#### 3. Create a null vector of size 10 (★☆☆)

In [5]:
vector = np.zeros(10)
print(vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [8]:
arraySize = vector.nbytes
print(f'{arraySize} bytes')

80 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [13]:
#help(np.add)
np.add?

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [14]:
vector_1 = np.zeros(10)
vector_1[4] = 1
print(vector_1)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [21]:
vector_2 = np.arange(10, 50)
print(vector_2)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [22]:
vector_2 = vector_2[::-1]
print(vector_2)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [29]:
matrix = np.arange(9).reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [31]:
vector_3 = np.array([1,2,0,0,4,0])
non_zero_emement_index = np.nonzero(vector_3)
print(non_zero_emement_index)

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [32]:
matrix_2 = np.eye(3)
print(matrix_2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [34]:
matrix_3 = np.random.rand(3, 3, 3)
print(matrix_3)

[[[0.12340967 0.14105678 0.17202402]
  [0.30786306 0.53038077 0.46636577]
  [0.57893193 0.40122342 0.47742443]]

 [[0.28148713 0.53922376 0.41746975]
  [0.96738707 0.28163356 0.8801243 ]
  [0.07896383 0.31525596 0.14049095]]

 [[0.45943694 0.97009682 0.85267019]
  [0.369646   0.02098028 0.21797465]
  [0.99730623 0.10989625 0.63685456]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [36]:
matrix_4 = np.random.randint(low=0, high=100, size=(10, 10))

min_val = matrix_4.min()
max_val = matrix_4.max()

print(matrix_4)

print("Minimum value in matrix_4:", min_val)
print("Maximum value in matrix_4:", max_val)

[[39 30 62 96 30 34 50 44 34 61]
 [78 54 32 77 52 82 68 87  8 98]
 [88 49 14 70 52  7 85 73 62 93]
 [44 72 81  3 84 93 29 22 64 76]
 [36 27 82 37 42  6 78 37  7 88]
 [50 22 66 67 89 93 92 38  0 10]
 [21  8 37 65 64  7 97 13 41 54]
 [88  3 57 16  8 11 18 89  6 50]
 [21 25 52  2 42 25 79 55 54 69]
 [44 40 47 93 23 82  2 17 45 39]]
Minimum value in matrix_4: 0
Maximum value in matrix_4: 98


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [46]:
vector_4 = np.arange(0,30)
vector_4_mean = vector_4.mean()
print(vector_4_mean)

14.5


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [47]:
rows = 3
cols = 3

arr = np.ones((rows, cols))

arr[1:-1, 1:-1] = 0

print(arr)

[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [48]:
#exapme array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

#add a border of 0s
arr_with_border = np.pad(arr, pad_width=1, mode='constant', constant_values=0)

print(arr_with_border)

[[0 0 0 0 0]
 [0 1 2 3 0]
 [0 4 5 6 0]
 [0 0 0 0 0]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [3]:
a = 0 * np.nan
print(a)

b = np.nan == np.nan
print(b)

c = np.inf > np.nan
print(c)

d = np.nan - np.nan
print(d)

e = np.nan in set([np.nan])
print(e)

f = 0.3 == 3 * 0.1
print(f)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [4]:
arr = np.zeros((5, 5))

arr[1, 0] = 1
arr[2, 1] = 2
arr[3, 2] = 3
arr[4, 3] = 4

print(arr)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [5]:
matrix = np.zeros((8, 8), dtype=int)

# Wypełniamy macierz wzorem szachownicy przy użyciu pętli for
for i in range(8):
    for j in range(8):
        # Jeśli suma indeksów jest nieparzysta, wstawiamy 1
        if (i+j) % 2 != 0:
            matrix[i][j] = 1

print(matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [7]:
# Tworzymy tablicę o kształcie (6, 7, 8) wypełnioną wartościami od 0 do 335
arr = np.arange(6*7*8).reshape(6, 7, 8)

# Konwertujemy indeks elementu 100 na trójki indeksów (x, y, z) przy użyciu funkcji np.unravel_index()
index = np.unravel_index(100, arr.shape)

# Wyświetlamy indeks (x, y, z) elementu 100
print(index)

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [8]:
template = np.array([[0, 1], [1, 0]])

# Powiela każdy element macierzy 4 razy, aby utworzyć macierz 8x8
matrix = np.tile(template, (4, 4))

# Wyświetlamy macierz
print(matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [9]:
# Tworzymy losową macierz 5x5
matrix = np.random.rand(5, 5)

# Normalizujemy macierz, aby każdy wiersz miał średnią 0 i odchylenie standardowe 1
normalized_matrix = (matrix - np.mean(matrix, axis=1, keepdims=True)) / np.std(matrix, axis=1, keepdims=True)

# Wyświetlamy macierz przed i po normalizacji
print("Macierz przed normalizacją:")
print(matrix)
print("\nMacierz po normalizacji:")
print(normalized_matrix)

Macierz przed normalizacją:
[[0.72069709 0.58440571 0.45155586 0.07189766 0.1546612 ]
 [0.23030765 0.11213129 0.07259254 0.71441288 0.32077719]
 [0.9138239  0.50789314 0.54869457 0.98898138 0.59923242]
 [0.84124869 0.68925831 0.86629662 0.30070086 0.34926463]
 [0.3231424  0.29450369 0.05529244 0.58589826 0.77698648]]

Macierz po normalizacji:
[[ 1.30714377  0.75738151  0.22150145 -1.30993613 -0.97609059]
 [-0.26019725 -0.7749425  -0.94716294  1.84843832  0.13386437]
 [ 1.01431514 -1.02301353 -0.81823494  1.3915235  -0.56459016]
 [ 0.96440102  0.33230561  1.06856997 -1.28362147 -1.08165513]
 [-0.33620729 -0.45080244 -1.40798417  0.71518603  1.47980787]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [10]:
# Tworzymy niestandardowy typ danych RGBA jako 4 niepodpisane bajty (unsigned byte)
# Używamy notacji "<" jako little-endian byte order, a następnie 4 "B" do opisu 4 niepodpisanych bajtów
rgba_dtype = np.dtype([("r", np.ubyte), ("g", np.ubyte), ("b", np.ubyte), ("a", np.ubyte)])

# Testujemy niestandardowy typ danych, tworząc macierz RGBA
color_matrix = np.array([(255, 0, 0, 255), (0, 255, 0, 255), (0, 0, 255, 255)], dtype=rgba_dtype)

# Wyświetlamy macierz kolorów
print(color_matrix)

[(255,   0,   0, 255) (  0, 255,   0, 255) (  0,   0, 255, 255)]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [11]:
# Tworzymy macierze 5x3 i 3x2 z losowymi wartościami
matrix_1 = np.random.rand(5, 3)
matrix_2 = np.random.rand(3, 2)

# Mnożenie macierzy za pomocą funkcji numpy.dot()
product_dot = np.dot(matrix_1, matrix_2)

# Mnożenie macierzy za pomocą metody @
product_at = matrix_1 @ matrix_2

# Wyświetlenie wynikowych macierzy
print("Macierz 1:")
print(matrix_1)
print("\nMacierz 2:")
print(matrix_2)
print("\nWynik mnożenia macierzy za pomocą numpy.dot():")
print(product_dot)
print("\nWynik mnożenia macierzy za pomocą metody @:")
print(product_at)

Macierz 1:
[[0.18379914 0.55153617 0.36485845]
 [0.37442315 0.67676592 0.19930126]
 [0.98503376 0.23507422 0.85425789]
 [0.90528213 0.45847401 0.01141389]
 [0.88314535 0.02129231 0.68483919]]

Macierz 2:
[[0.77085927 0.81253365]
 [0.39917328 0.4041614 ]
 [0.02707805 0.73811308]]

Wynik mnożenia macierzy za pomocą numpy.dot():
[[0.37172143 0.64155941]
 [0.56417112 0.72486094]
 [0.87628939 1.52591993]
 [0.88116476 0.92929443]
 [0.7078242  1.23167961]]

Wynik mnożenia macierzy za pomocą metody @:
[[0.37172143 0.64155941]
 [0.56417112 0.72486094]
 [0.87628939 1.52591993]
 [0.88116476 0.92929443]
 [0.7078242  1.23167961]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [13]:
arr = np.random.randint(0, 10, size=10)
print("Tablica przed negacją:")
print(arr)

# negacja elementów pomiędzy wartośćiami 3 a 8
arr[(arr > 3) & (arr < 8)] *= -1

print("Tablica po negacji:")
print(arr)

Tablica przed negacją:
[7 3 8 9 7 2 1 9 3 2]
Tablica po negacji:
[-7  3  8  9 -7  2  1  9  3  2]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [14]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

'''
W pierwszej linii kodu używamy funkcji sum() wbudowanej w Pythona, aby dodać liczby od 0 do 4 do -1. Wynik to 9.

W drugiej linii kodu używamy funkcji sum() z biblioteki NumPy do dodawania elementów wzdłuż 
osi -1 (czyli ostatniej osi) w tablicy z wartościami od 0 do 4. Wynik to 10, ponieważ oś -1 w tablicy 
to jedyny wymiar tej tablicy, a suma elementów wzdłuż 
jedynowymiarowej tablicy to suma wszystkich jej elementów.

'''

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [15]:
#Wszystkie wyrażenia z wyjątkiem Z < Z > Z są dozwolone

'''
Z**Z podnosi każdy element wektora Z do potęgi elementu o tym samym indeksie i zwraca nowy wektor z wynikami.
2 << Z >> 2 przesuwa binarnie wszystkie elementy wektora Z o 2 bity w lewo, a następnie o 2 bity w prawo, 
zwracając nowy wektor z wynikami. To działa poprawnie, ponieważ przesunięcia bitowe wymagają, aby wartości
były całkowite.

Z <- Z porównuje każdy element wektora Z z jego negacją i zwraca nowy wektor z wynikami (czyli True lub False),
co również jest dozwolone.

1j*Z mnoży każdy element wektora Z przez złożoną jednostkę urojoną 1j (równoważną sqrt(-1)) i zwraca wektor
liczb zespolonych z wynikami.

Z/1/1 dzieli każdy element wektora Z przez 1 a następnie przez 1 ponownie, co jest równoważne z podzieleniem
przez 1. Zwraca wektor z wartościami zmiennoprzecinkowymi z wynikami.

Z < Z > Z nie jest dozwolone, ponieważ Python nie obsługuje bezpośrednio porównań trójargumentowych, takich jak ten.
Potrzebujemy wykorzystać operatory logiczne, aby wyrażenie to było poprawne.
'''

'\nZ**Z podnosi każdy element wektora Z do potęgi elementu o tym samym indeksie i zwraca nowy wektor z wynikami.\n2 << Z >> 2 przesuwa binarnie wszystkie elementy wektora Z o 2 bity w lewo, a następnie o 2 bity w prawo, \nzwracając nowy wektor z wynikami. To działa poprawnie, ponieważ przesunięcia bitowe wymagają, aby wartości\nbyły całkowite.\n\nZ <- Z porównuje każdy element wektora Z z jego negacją i zwraca nowy wektor z wynikami (czyli True lub False),\nco również jest dozwolone.\n\n1j*Z mnoży każdy element wektora Z przez złożoną jednostkę urojoną 1j (równoważną sqrt(-1)) i zwraca wektor\nliczb zespolonych z wynikami.\n\nZ/1/1 dzieli każdy element wektora Z przez 1 a następnie przez 1 ponownie, co jest równoważne z podzieleniem\nprzez 1. Zwraca wektor z wartościami zmiennoprzecinkowymi z wynikami.\n\nZ < Z > Z nie jest dozwolone, ponieważ Python nie obsługuje bezpośrednio porównań trójargumentowych, takich jak ten.\nPotrzebujemy wykorzystać operatory logiczne, aby wyrażenie to był

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [16]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/var/folders/qf/kbhtb9x91vl6xcmh2r595c_h0000gp/T/ipykernel_878/3912170336.py:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
/var/folders/qf/kbhtb9x91vl6xcmh2r595c_h0000gp/T/ipykernel_878/3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


#### 29. How to round away from zero a float array ? (★☆☆)

In [ ]:
# by zaokrąglić wartości w tablicy liczb zmiennoprzecinkowych w kierunku ujemnych lub dodatnich liczb całkowitych, 
# można użyć funkcji numpy.copysign() oraz numpy.ceil() lub numpy.floor(). Funkcja numpy.copysign() zwraca tablicę
# z wartościami wejściowymi oraz znakami elementów tablicy wynikowej, 
# a funkcja numpy.ceil() lub numpy.floor() zaokrągla wartości do najbliższej liczby całkowitej.

#### 30. How to find common values between two arrays? (★☆☆)

In [ ]:
# Aby znaleźć wartości wspólne między dwoma tablicami numpy, można użyć funkcji numpy.intersect1d().

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
# Ignorowanie wszystkich ostrzeżeń biblioteki NumPy nie jest zalecane, ponieważ może to prowadzić do utraty 
# ważnych informacji diagnostycznych. Wartości ostrzeżeń z biblioteki NumPy mogą wskazywać na problemy związane
# z typami danych, arytmetyką lub innymi aspektami obliczeń numerycznych.

# Jednakże, jeśli z jakiegoś powodu chcesz zignorować wszystkie ostrzeżenia, można to zrobić za pomocą metody 
# filterwarnings() z modułu warnings.

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [17]:
print(np.sqrt(-1) == np.emath.sqrt(-1))

False


/var/folders/qf/kbhtb9x91vl6xcmh2r595c_h0000gp/T/ipykernel_878/2770867030.py:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1) == np.emath.sqrt(-1))


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [18]:
# dzisiejsza data
today = np.datetime64('today', 'D')

# wczorajsza data
yesterday = today - np.timedelta64(1, 'D')

# jutrzejsza data
tomorrow = today + np.timedelta64(1, 'D')

# wyświetlenie dat
print('Dzisiaj:', today)
print('Wczoraj:', yesterday)
print('Jutro:', tomorrow)

Dzisiaj: 2023-04-01
Wczoraj: 2023-03-31
Jutro: 2023-04-02


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)